/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddElm: typeof import('./src/components/addElm.vue')['default']
    ChangeElm: typeof import('./src/components/changeElm.vue')['default']
    copy: typeof import('./src/components/addElm copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
